#-------------------------------
# General Site Settings

title: Portfolio
description: Urbanist . Designer . Coder
email: patrickm02L@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About, url: '#about'}
- {name: Work, url: '#work'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'This is the Portfolio of Patrick McDonnell aka patrickm02L'
  rel-author: 'https://plus.google.com/+Patrickm02l/'
  rel-publisher: 'https://plus.google.com/+Patrickm02l/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: UA-53246637-1

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Patrick specializes in making things** for human people.
  He definitely makes [Designs](https://issuu.com/patrickm02l){:target="_blank"} and [Codes](https://github.com/patrickm02L){:target="_blank"},
  but he also puts effort into crafting [Super Tight Digital Shorts](https://www.youtube.com/user/patrickm02L/){:target="_blank"}
  and [Grammin'](https://www.instagram.com/patrickm02l/){:target="_blank"} the street, events, projects, adventures, cool peeps, and life.


skills:
- {name: Communication, value: '8'}
- {name: Organization, value: '9'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '7'}
- {name: Planning, value: '9'}
- {name: Visual Design, value: '8'}
- {name: UX Design, value: '7'}
- {name: Programming, value: '5'}

#-------------------------------
# Work Section

projects:
- {name: Swing Park, folder: 'swingpark', file: 'work/swingpark.html'}
- {name: Balançoire, folder: 'balancoire', file: 'work/balancoire.html'}
- {name: Living Plaza, folder: 'living-plaza', file: 'work/living-plaza.html'}
- {name: Cardboard Animal Picinic, folder: 'cardboard-animal-picnic', file: 'work/cardboard-animal-picnic.html'}
- {name: Bookworm Mini Parklet, folder: 'bookworm', file: 'work/bookworm.html'}
- {name: Ice Cream Stage, folder: 'ice-cream-stage', file: 'work/ice-cream-stage.html'}
- {name: Chalktoberfest, folder: 'chalktoberfest', file: 'work/chalktoberfest.html'}
- {name: Busking Day, folder: 'busking-day', file: 'work/busking-day.html'}
- {name: Party in the Park, folder: 'party-in-the-park', file: 'work/party-in-the-park.html'}
- {name: Festivus of Lights, folder: 'festivus', file: 'work/festivus.html'}
- {name: Urban Studio, folder: 'urban-studio', file: 'work/urban-studio.html'}
- {name: Clark and Diana, folder: 'clark-and-diana', file: 'work/clark-and-diana.html'}
- {name: Miles, folder: 'miles', file: 'work/miles.html'}
- {name: Dallas Visual Timeline, folder: 'dallas-visual-timeline', file: 'work/dallas-visual-timeline.html'}
- {name: Black Lunch Tables, folder: 'black-lunch-tables', file: 'work/black-lunch-tables.html'}
- {name: The Yard, folder: 'the-yard', file: 'work/the-yard.html'}
- {name: Kit-O-Cart, folder: 'kitocart', file: 'work/kitocart.html'}
- {name: Hopscotch, folder: 'hopscotch', file: 'work/hopscotch.html'}
#- {name: Neighborhood Murals, folder: 'neighborhood-murals', file: 'work/neighborhood-murals.html'}
#- {name: Blind Field Shuttle, folder: 'blind-field-shuttle', file: 'work/blind-field-shuttle.html'}
#- {name: On Hamburger Square, folder: 'on-hamburger-square', file: 'work/on-hamburger-square.html'}
#- {name: Tape Maze, folder: 'tape-maze', file: 'work/tape-maze.html'}
- {name: Inspector Gadget, folder: 'inspector-gadget', file: 'work/inspector-gadget.html'}
#- {name: Gate City Sign, folder: 'gate-city-sign', file: 'work/gate-city-sign.html'}

#-------------------------------
# Clients Section


#clients:
#- {avatar: 'face-aaroni.jpg',
#  name: 'Scott Summers',
#  title: 'Director of Design, OnToText Ind.',
#  quote: '<p><strong>While we all felt that Travis was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>',
#  logo: 'logo1.png'}
#- {avatar: 'face-atariboy.jpg',
#  name: 'Hank McCoy',
#  title: 'Eater of Salad, Antartica Int.',
#  quote: '<p><strong>Working with Travis was the highlight of my career.</strong> Other moments of note were collecting the largest number of paperclips in the office, and winning a trophy for saying "uh huh, and then what?" 30 times in a row to my girlfriend without her noticing.</p>',
#  logo: 'logo2.png'}
#- {avatar: 'face-jackiesaik.jpg',
#  name: 'Stacy Lang',
#  title: 'Social Media Girl, Quebec Int.',
#  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
#  logo: 'logo3.png'}
#- {avatar: 'face-teleject.jpg',
#  name: 'Cleatus Cassidy',
#  title: 'VP of Helmut, Lorem Sorem LLC.',
#  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
#  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/patrickm02L'}
- {icon: 'instagram', link: 'https://www.instagram.com/patrickm02l/'}
- {icon: 'youtube', link: 'https://www.youtube.com/user/patrickm02L'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/patrickm02l'}
- {icon: 'github', link: 'https://github.com/patrickm02L'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
